name       : gpart
version    : 0.3
release    : 2
source     :
    - https://github.com/baruch/gpart/archive/0.3.tar.gz : ec56d12ec9ffdb9877c12692ea6e51620b1ae44473d3d253b27fc31ed9ebb4dd
license    : GPL-2.0-or-later
component  : system.utils
summary    : Gpart is a small tool which tries to guess what partitions are there on a drive.
description: |
    Gpart is a small tool which tries to guess what partitions are on a PC type, MBR-partitioned hard disk in case the primary partition table was damaged.

    Gpart works by scanning through the device (or file) given on the command line on a sector basis. Each guessing module is asked if it thinks a filesystem it knows about could start at a given sector. Several filesystem guessing modules are built in.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
